version: "3.8"

services:
  backend:
    build: ./backend
    container_name: fastify-backend
    ports:
      - "3000:3000"
    environment:
      DATABASE_HOST: db
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_NAME: productos_db
      DATABASE_PORT: 5432
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: fastify-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: productos_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:

